import type { Metadata } from 'next'
import Link from 'next/link'
import { IoArrowBackSharp } from 'react-icons/io5'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <Link href={'/'}>
        <button className='group absolute left-4 top-4 flex items-center gap-x-2 rounded-[25px] border-[1px] border-indigo-600 px-5 py-2 text-white transition-all duration-500 hover:bg-indigo-600'>
          <IoArrowBackSharp className='duration-300 group-hover:-translate-x-2' />
          <p>Back to Home</p>
        </button>
      </Link>
      <div>{children}</div>
    </div>
  )
}
